version: '3'

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.0
    volumes:
      - /home/severadmin/docker_volumes/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/logs:/var/logs
      - /home/severadmin/docker_volumes/promtail:etc/promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    user: "1000"
    volumes:

    port:  
